#!/bin/bash

_echot "------- update"
${_CMD} update

_echot "------- dist-upgrade"
${_CMD} -y dist-upgrade

# _echot "------- clean"
# ${_CMD} -y autoremove
# ${_CMD} clean
# ${_CMD} autoclean

_echot "------- password"
_echoA "Remove kept passwords in file: ${_FILE_CONF}"

########################  END

_partadd "${_PART}" "${_FILE_DONE}"

########################  RESTART

_echoA "Restart your computer to append configuration"
_askno "Validate to reboot"
sudo reboot
