#!/bin/bash
#
# write by Aguy

########################  REPOSITORIES

_echot "------- apt repository"
file=/etc/apt/sources.list
_keepcp ${file}

sudo add-apt-repository -yn ppa:mozillateam/ppa # mozilla
sudo apt update

########################  MAIN

_echot "------- system"
packages="build-essential curl exfat-utils gnupg2 lnav hfsprogs htop kpartx most ncdu pv testdisk tree"
packages+=" gdebi gparted tmux vim"
packages+=" p7zip-full p7zip-rar zip unzip rar unrar"
# oracle-java7-installer ntfsprogs grsync gtk2-engines-pixbuf libnss-myhostname atop fslint dstat icedtea-8-plugin
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- tools"
packages="dconf-editor meld qt5ct"
packages+=" thunar-media-tags-plugin tumbler-plugins-extra"
packages+=" galculator gnome-tweak-tool"
#   gnome-system-tools
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- libreoffice"
packages="libreoffice"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- video"
packages="mpv simplescreenrecorder"
# cheese
packages+=" gstreamer1.0-plugins-bad libavcodec-extra libdvdnav4 libdvd-pkg libdvdread4 ubuntu-restricted-extras"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
