#!/bin/bash

_echot "------- packages"
packages="git swig libjpeg-dev zlib1g-dev libffi-dev libssl-dev uml-utilities"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- python"
packages="python python-pip python-dev"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- pip2"
packages="pip setuptools"
python -m pip install -U ${packages} && _partadd "${packages}" ${_FILE_PIP3} \
	|| { _echoE "Unable to pip2 install: ${packages}"; return 1; }
