#!/bin/bash

########################  SYSTEM

_echot "------- UTC 0"
_evalr rm /etc/localtime
_evalr ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime

########################  USER

_echot "------- user conf"
paths=".tmux .wxHexEditor .java/.userPrefs/us/deathmarine/luyten/"
for path in ${paths}; do
	_keepmv ${path}
done
for file in $(ls ${_PATH_BASE}/conf/user.*.tar.gz); do
	_eval tar xzf ${file} -C ${HOME}/
done

_echot "------- geany"
path=${HOME}/.config/geany/colorschemes
_keepmv ${path}
[ -d "${path}" ] || _eval mkdir -p ${path}
_eval  cp ${_PATH_BASE}/conf/geany/* ${path}/

_echot "------- bless"
path=${HOME}/.config/bless/layouts/
_keepmv ${path}
[ -d "${path}" ] || _eval mkdir -p ${path}
_eval cp ${_PATH_BASE}/conf/bless/* ${path}/
