#!/bin/bash

_echot "------- binary"
packages="bsdiff vbindiff"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- network"
packages="dnsutils net-tools netcat openssh-server traceroute whois xinetd"
packages+=" bmon darkstat dstat hping3 iftop ifstat tcpdump vnstat"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- hive"
packages="libhivex-bin chntpw reglookup"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- others"
packages="john libscca-utils pev radare2"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }


########################  PIP

_echot "------- pip2"
packages="balbuzard"
python -m pip install -U ${packages} && _partadd "${packages}" ${_FILE_PIP3} \
	|| { _echoE "Unable to pip2 install: ${packages}"; return 1; }

_echot "------- pip3"
packages="malcarve r2env regrippy"
python3 -m pip install -U ${packages} && _partadd "${packages}" ${_FILE_PIP3} \
	|| { _echoE "Unable to pip3 install: ${packages}"; return 1; }

########################  GIT

url=https://raw.githubusercontent.com/labcif/Base64SHA/master/b64sha
file=$( _get_curl b64sha ${url} )
_evalr cp ${file} /usr/local/bin/b64sha
_evalr chmod 755 /usr/local/bin/b64sha
