#!/bin/bash

########################  MAIN

_echot "------- forensic"
packages="binutils-common bsdmainutils pev radare2 bless wxhexeditor"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }
