#!/bin/bash

_echot "------- required files"
path_soft=idafree*_linux.run
while ! ls ${_PATH_SOFTS}/${path_soft} 2>/dev/null; do
	_echoA "Download file like '${path_soft}' \nand put it in path: ${_PATH_SOFTS}"
	_askyn "y to retry, n to abort"
	[ "${_ANSWER}" = n ] && return 1
done

_echot "------- packages i386"
packages="libc6-i686:i386 libexpat1:i386 libffi6:i386 libfontconfig1:i386 libfreetype6:i386 libgcc1:i386"
packages+=" libglib2.0-0:i386 libice6:i386 libpcre3:i386 libpng16-16:i386 libsm6:i386 libstdc++6:i386"
packages+=" libuuid1:i386 libx11-6:i386 libxau6:i386 libxcb1:i386 libxdmcp6:i386 libxext6:i386 libxrender1:i386"
packages+=" zlib1g:i386 libx11-xcb1:i386 libdbus-1-3:i386 libxi6:i386 libsm6:i386 libcurl4:i386"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- packages others"
packages="libgtk2.0-0:i386 gtk2-engines-murrine:i386 gtk2-engines-pixbuf:i386 libpango1.0-0:i386"
${_CMD_INS} ${packages} && _partadd "${packages}" ${_FILE_PCK} \
	|| { _echoE "Unable to install: ${packages}"; return 1; }

_echot "------- idafree"
file_soft=$( ls ${_PATH_SOFTS}/${path_soft} 2>/dev/null )
path=/opt/idafree
_evalr mkdir ${path}
_evalr chown ${USER}:${USER} ${path}
_echoA "After validation, give this path for installation: ${path}"
_askno "Validate to continue"
[ -w "${file_soft}" ] && _evalr chmod +x ${file_soft} 2>/dev/null
_eval sh ${file_soft}

_evalr ln -s ${path}/ida64 /usr/local/bin/idafree 
file=~/.local/share/applications/
[ -f "${file}" ] && _eval rm ${file}
_eval cp ${_PATH_BASE}/xtra/idafree.desktop  ~/.local/share/applications/
