#!/bin/bash

_echot "------- required files"
path_soft=luyten-*.tar.gz
while ! ls ${_PATH_SOFTS}/${path_soft} 2>/dev/null; do
	_echoA "Download file like '${path_soft}' \nand put it in path: ${_PATH_SOFTS}"
	_askyn "y to retry, n to abort"
	[ "${_ANSWER}" = n ] && return 1
done

_echot "------- luyten"
file_soft=$( ls ${_PATH_SOFTS}/${path_soft} 2>/dev/null )
path=/tmp/lt
[ -d "${path}" ] || _eval mkdir -p ${path}
_eval cd ${path}
_eval tar xzf "${file_soft}"
# wrong file
! [ -d opt ] && { _echoe "The file: ${file_soft} do not contains the good files"; return 1; }
_evalr mv opt/luyten* /opt/
_evalr mv usr/local/bin/luyten /usr/local/bin/
path=.java/.userPrefs/us/deathmarine/luyten
if ! [ -f ~/${path}/prefs.xml ]; then
	_eval mkdir -p ~/${path}
	_eval mv home/*/${path}/prefs.xml ~/${path}/
fi
_eval mv home/*/.local/share/applications/luyten.desktop ~/.local/share/applications/
_eval cd
_eval rm -fR ${path}
